services:
  back-end:
    image: server:latest
    container_name: server
    build: ./back-end
    restart: unless-stopped
    volumes:
    - ./back-end:/app
    - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - shortenurl
    depends_on:
      - db

  front-end:
    image: client:latest
    container_name: client
    build: ./front-end
    volumes:
      - ./front-end:/app
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - back-end
    networks:
      - shortenurl

  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortenurl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortenurl

volumes:
  postgres_data:

networks:
  shortenurl:
    driver: bridge